### PR TITLE
Fixes filter command and support filter feature in UG

### LINKED ISSUE #119: Filter command documentation does not match usage
In the filter command message usage, the accepted parameters is "[tag/TAG]... [t/TUTORIAL_GROUP_NUMBER]..." which suggest that `filter t/01 t/2` should work, but the following error message was produced "Multiple values specified for the following single-valued field(s): t/".

Should filter multiple conditions as `AND` while find multiple conditions work as `OR`? Since a person can only belong to a single tutorial group, the above command being an error could be valid.

### LINKED ISSUE #123: Filter does not accept multiple leading zeros
The command `filter t/001` does not work even though it is between 1 - 99.

### LINKED ISSUE #149: Filter may behave oddly if the user expects partial tag matching
Example:
filter tag/fri
If users expect substring matching but only exact tag matching is implemented, they may report this as a bug.

### PR DESCRIPTION
**Pull request by XZHHHHHH**
Fixes #119
Fixes #123
Fixes #149

## Summary

Document the `filter` feature in the User Guide, correct its format description so it matches actual behavior, and fix the `filter` parser to accept tutorial groups with leading zeros.

## Changes

- Added a `filter` entry to the command summary in `UserGuide.md`.
- Added a dedicated `filter` section between the `edit` and `find` sections.
- Documented the correct format as:
  - `filter [tag/TAG]... [t/TUTORIAL_GROUP_NUMBER]`
- Clarified that:
  - `tag/` can be repeated to filter by multiple tags.
  - `t/` is a single tutorial-group filter and cannot be repeated.
- Added examples such as:
  - `filter tag/friend`
  - `filter t/01`
  - `filter tag/friend tag/mentor`
  - `filter tag/friend t/01`
- Updated `FilterCommandParser` to accept tutorial-group inputs with leading zeros, such as `t/001`.
- Removed the stricter filter-specific tutorial-group validation so `filter` now follows the same tutorial-group parsing rules used elsewhere.
- Updated `FilterCommandParserTest` to cover successful parsing of tutorial groups with leading zeros.
- Updated `UserGuide.md` to explicitly state that values such as `t/1`, `t/01`, and `t/001` are accepted.
- Clarified the intended command design: keep `filter` exact and keep `find` flexible, so substring-style matching is not part of this change.

## Why

Previously, the `filter` feature was not documented in the User Guide, and the format could be misunderstood as allowing multiple tutorial-group prefixes. In addition, the `filter` command incorrectly rejected tutorial-group inputs with leading zeros such as `t/001`, even though leading zeros are allowed by the tutorial-group model. These updates make the documentation and command behavior consistent and reduce confusion for users. Concerns about substring matching are not relevant to this change, since the intended design is to keep `filter` exact and keep `find` flexible.

## Testing

- Added parser test coverage for tutorial groups with leading zeros.
- Ran `./gradlew test --tests "cms.logic.parser.FilterCommandParserTest"` successfully.

## User-visible behavior

- Users can now find `filter` in the User Guide.
- The guide clearly explains how to use `filter`.
- The guide no longer suggests that multiple tutorial-group prefixes are valid.
- The `filter` command now accepts tutorial-group inputs with leading zeros, such as `t/001`.
- `filter` remains an exact-match command, while `find` remains the flexible search command.

### CODE REVIEW

File: src/main/java/cms/logic/parser/FilterCommandParser.java [hunk 1]
```diff
@@ -62,14 +61,14 @@ private Set<TutorialGroup> parseTutorialGroups(List<String> rawTutorialGroups) t
 
     /**
      * Parses tutorial group input for the filter command.
-     * Filter users enter groups as 1-99, with an optional leading zero.
+     * Filter users enter groups as 1-99, with leading zeros allowed.
      * Canonicalisation is handled by {@code TutorialGroup}.
      */
     private TutorialGroup parseFilterTutorialGroup(String rawTutorialGroup) throws ParseException {
```
Comment (YeeShin504) [inline src/main/java/cms/logic/parser/FilterCommandParser.java]: Is there a reason why the parseTutorialGroup and parseRags from ParserUtil is not used instead?

Comment (YeeShin504) [reply src/main/java/cms/logic/parser/FilterCommandParser.java]: When communicating in the UG, will we have 2 standards (leading 0s allowed in add, but not in filter)? I think it would be good to unify them to provide a better user experience. I am open to rejecting the leading 0s too.
