### PR TITLE
Fix bugs for delete feature

### LINKED ISSUE #136: Delete command does not accept whitespaces between prefix and id
Image
Should this be an valid input? Currently it is not accepted.

### LINKED ISSUE #137: Delete command accepts duplicate indexes and IDs
`delete 1 1 1 1 1` and `delete id/A7788990V A7788990V` is accepted, should there be a warning or error message? Assuming the user made a typo and meant to delete another index or id instead.

### PR DESCRIPTION
**Pull request by XZHHHHHH**
Fixes #136
Fixes #137 

## Summary

Improve the `delete` command by accepting whitespace after the `m/` prefix for matric-based deletion, and clarify duplicate-target handling with explicit warning messages instead of treating duplicates as errors.

## Changes

- Updated `DeleteCommandParser` to accept whitespace after the `m/` prefix.
- Improved parsing for matric-based delete inputs such as:
  - `delete m/ A0123456J`
  - `delete m/ A0123456J A0234567X`
- Added warning feedback for duplicate delete targets instead of rejecting them.
- Duplicate delete inputs such as the following are now accepted and handled gracefully:
  - `delete 1 1 1 1 1`
  - `delete m/A0123456J A0123456J`
- Updated `DeleteCommand` result messages so duplicate targets are deleted only once and a warning is shown to the user.
- Added `hashCode()` to `Index` so duplicate index detection works correctly for real parsed input.
- Kept existing delete behavior unchanged for:
  - index-based deletion
  - standard matric-based deletion without extra whitespace
  - repeated matric-prefix deletion
  - valid duplicate targets being deleted only once

- Updated `DeleteCommandParserTest` to cover the new whitespace-tolerant parsing paths.
- Updated `DeleteCommandTest` to cover duplicate index and duplicate matric warning messages.
- Updated `IndexTest` to verify the `equals`/`hashCode` contract needed for duplicate index detection.

## Why

Previously, the `delete` command was unnecessarily strict about whitespace after `m/`, so inputs like `delete m/ A0123456J` were rejected even though the identifier itself was valid. In addition, duplicate delete targets were accepted implicitly but gave no clear feedback to the user, which could hide accidental repeated input. These changes make the command more forgiving for harmless spacing issues while also making duplicate-target behavior explicit and visible through warning messages.

## Testing

- Added parser test coverage for whitespace after `m/` in `DeleteCommandParserTest`.
- Added command test coverage for duplicate index and duplicate matric warnings in `DeleteCommandTest`.
- Added `IndexTest` coverage for `hashCode()` consistency with `equals()`.
- Ran ./gradlew check coverage successfully.

## User-visible behavior

- Users can now run matric-based delete commands with whitespace after `m/`.
- Inputs such as `delete m/ A0123456J` now work.
- Duplicate delete targets are still accepted and deleted only once.
- The app now shows a warning when duplicate delete targets are detected and ignored.
- Existing valid delete commands continue to behave as before.

### CODE REVIEW

File: src/main/java/cms/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -112,6 +118,20 @@ private String formatDeletedPersons(List<Person> deletedPersons, boolean isMaske
                 .collect(Collectors.joining("\n"));
     }
 
+    private int getDuplicateTargetCount() {
```
Comment (YeeShin504) [inline src/main/java/cms/logic/commands/DeleteCommand.java]: Did you canonicalise the input before passing to deduplication using hash set?
